### ISSUE TITLE
Improve the way font files are setted

### ISSUE THREAD

**Issue by FallenDoll** [WorldObservationLog/Akiwa#3]
For now, set font files involves manually specifying the file path and adding the font using `fontManager.addFont`
https://github.com/WorldObservationLog/Akiwa/blob/1588fdb7a26617073c19f1bcb20cb997d8bea088/src/analysis/chart.py#L16

Shall we improve this way by using `font_manager.findSystemFonts`.?
This has the following advantages:
- We can eliminate the need for specifying fonts, reducing the required configuration settings in the config file and easing the cognitive load on the user.
- It's more friendly for Dockerize which eliminating the need to specify file formats and requiring only the specification of the 'font' directory.

IMO, we can establish a 'font' directory, allowing users to place any font files within it. We can then retrieve them using the `font_manager.findSystemFonts method.` If no fonts are found, at least we can fallback to using the system fonts. like

```python
import matplotlib.pyplot as plt
from matplotlib import font_manager

font_dirs = ["./fonts"]  # The path to the custom font file.
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    font_manager.fontManager.addfont(font_file)
# or just get the first one
```

**Comment by WorldObservationLog** [comment]
now can use both font path and font name
